name = "FrameXAct"
author = "Victor Oliver"
version = "19-0.0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d54f4093c3cc702b7102b1c6531ab8cfe5fc74f549ee32290bb74b7309450af"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
