name = "FrameXAct"
author = "Victor Oliver"
version = "18-0.0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3c6021640d7068f3a39908f60ab9714fbb946a0f792549c43cefb5f2698a15f"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
